apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  namespace: juiceshop
spec:
  replicas: 1
  selector:
    matchLabels: { app: juiceshop }
  template:
    metadata:
      labels: { app: juiceshop }
    spec:
      containers:
        - name: juiceshop
          image: ${IMAGE}
          ports: [{ containerPort: 3000 }]
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
